export interface ThemeVariant {
  '--color-bg-primary': string;
  '--color-bg-secondary': string;
  '--color-bg-tertiary': string;
  '--color-bg-card': string;
  '--color-bg-hover': string;
  '--color-bg-elevated': string;
  '--color-text-primary': string;
  '--color-text-secondary': string;
  '--color-text-muted': string;
  '--color-text-inverse': string;
  '--color-accent': string;
  '--color-accent-hover': string;
  '--color-border': string;
  '--color-border-light': string;
  '--color-border-focus': string;
  '--color-sidebar-bg': string;
  '--color-sidebar-hover': string;
  '--color-sidebar-active': string;
  '--color-header-bg': string;
}

export interface Theme {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  dark: ThemeVariant;
  light: ThemeVariant;
}

export const themes: Theme[] = [
  {
    id: 'amber',
    name: 'عنبر غامق',
    nameEn: 'Amber Noir',
    description: 'الكلاسيكي الدافئ — مزيج البنفسجي العميق والعنبر الذهبي',
    dark: {
      '--color-bg-primary': '#0C0816',
      '--color-bg-secondary': '#161025',
      '--color-bg-tertiary': '#1F1730',
      '--color-bg-card': '#18122B',
      '--color-bg-hover': '#251C3A',
      '--color-bg-elevated': '#201836',
      '--color-text-primary': '#F0EDEE',
      '--color-text-secondary': '#AA9FB3',
      '--color-text-muted': '#7A6E7E',
      '--color-text-inverse': '#0C0816',
      '--color-accent': '#D4893B',
      '--color-accent-hover': '#E0984E',
      '--color-border': '#2A2240',
      '--color-border-light': '#362C50',
      '--color-border-focus': '#D4893B',
      '--color-sidebar-bg': '#0A0712',
      '--color-sidebar-hover': '#161025',
      '--color-sidebar-active': 'rgba(212, 137, 59, 0.12)',
      '--color-header-bg': 'rgba(12, 8, 22, 0.85)',
    },
    light: {
      '--color-bg-primary': '#F8F9FA',
      '--color-bg-secondary': '#F1F3F5',
      '--color-bg-tertiary': '#E9ECEF',
      '--color-bg-card': '#FFFFFF',
      '--color-bg-hover': '#F1F3F5',
      '--color-bg-elevated': '#FFFFFF',
      '--color-text-primary': '#1A1D21',
      '--color-text-secondary': '#6B7280',
      '--color-text-muted': '#9CA3AF',
      '--color-text-inverse': '#FFFFFF',
      '--color-accent': '#2563EB',
      '--color-accent-hover': '#1D4ED8',
      '--color-border': '#E5E7EB',
      '--color-border-light': '#F3F4F6',
      '--color-border-focus': '#2563EB',
      '--color-sidebar-bg': '#1A1D21',
      '--color-sidebar-hover': '#2A2D31',
      '--color-sidebar-active': 'rgba(37, 99, 235, 0.12)',
      '--color-header-bg': 'rgba(255, 255, 255, 0.9)',
    },
  },
  {
    id: 'teal',
    name: 'نيلي غامق',
    nameEn: 'Teal Dusk',
    description: 'بارد احترافي — أزرق نيلي مع لمسات خضراء',
    dark: {
      '--color-bg-primary': '#0B1413',
      '--color-bg-secondary': '#121E1D',
      '--color-bg-tertiary': '#182826',
      '--color-bg-card': '#0F1C1A',
      '--color-bg-hover': '#1C2E2C',
      '--color-bg-elevated': '#182826',
      '--color-text-primary': '#ECF1F0',
      '--color-text-secondary': '#A3B5B2',
      '--color-text-muted': '#6D7D7A',
      '--color-text-inverse': '#0B1413',
      '--color-accent': '#2A9D8F',
      '--color-accent-hover': '#35B0A1',
      '--color-border': '#1C2E2C',
      '--color-border-light': '#253A38',
      '--color-border-focus': '#2A9D8F',
      '--color-sidebar-bg': '#091110',
      '--color-sidebar-hover': '#121E1D',
      '--color-sidebar-active': 'rgba(42, 157, 143, 0.12)',
      '--color-header-bg': 'rgba(11, 20, 19, 0.85)',
    },
    light: {
      '--color-bg-primary': '#F8F9FA',
      '--color-bg-secondary': '#F1F3F5',
      '--color-bg-tertiary': '#E9ECEF',
      '--color-bg-card': '#FFFFFF',
      '--color-bg-hover': '#F1F3F5',
      '--color-bg-elevated': '#FFFFFF',
      '--color-text-primary': '#1A1D21',
      '--color-text-secondary': '#6B7280',
      '--color-text-muted': '#9CA3AF',
      '--color-text-inverse': '#FFFFFF',
      '--color-accent': '#0D9488',
      '--color-accent-hover': '#0B7A70',
      '--color-border': '#E5E7EB',
      '--color-border-light': '#F3F4F6',
      '--color-border-focus': '#0D9488',
      '--color-sidebar-bg': '#134E48',
      '--color-sidebar-hover': '#1A6B62',
      '--color-sidebar-active': 'rgba(13, 148, 136, 0.12)',
      '--color-header-bg': 'rgba(255, 255, 255, 0.9)',
    },
  },
  {
    id: 'rose',
    name: 'وردي غامق',
    nameEn: 'Rose Noir',
    description: 'جريء مميز — خمري عميق مع وردي دافئ',
    dark: {
      '--color-bg-primary': '#160A10',
      '--color-bg-secondary': '#201219',
      '--color-bg-tertiary': '#2A1A22',
      '--color-bg-card': '#1C1017',
      '--color-bg-hover': '#301E27',
      '--color-bg-elevated': '#2A1A22',
      '--color-text-primary': '#F0EBED',
      '--color-text-secondary': '#B3A2A9',
      '--color-text-muted': '#7A6970',
      '--color-text-inverse': '#160A10',
      '--color-accent': '#D45A7A',
      '--color-accent-hover': '#E06C8A',
      '--color-border': '#301E27',
      '--color-border-light': '#3C2631',
      '--color-border-focus': '#D45A7A',
      '--color-sidebar-bg': '#12080D',
      '--color-sidebar-hover': '#201219',
      '--color-sidebar-active': 'rgba(212, 90, 122, 0.12)',
      '--color-header-bg': 'rgba(22, 10, 16, 0.85)',
    },
    light: {
      '--color-bg-primary': '#F8F9FA',
      '--color-bg-secondary': '#F1F3F5',
      '--color-bg-tertiary': '#E9ECEF',
      '--color-bg-card': '#FFFFFF',
      '--color-bg-hover': '#F1F3F5',
      '--color-bg-elevated': '#FFFFFF',
      '--color-text-primary': '#1A1D21',
      '--color-text-secondary': '#6B7280',
      '--color-text-muted': '#9CA3AF',
      '--color-text-inverse': '#FFFFFF',
      '--color-accent': '#E11D48',
      '--color-accent-hover': '#BE123C',
      '--color-border': '#E5E7EB',
      '--color-border-light': '#F3F4F6',
      '--color-border-focus': '#E11D48',
      '--color-sidebar-bg': '#4C0519',
      '--color-sidebar-hover': '#6B0C2A',
      '--color-sidebar-active': 'rgba(225, 29, 72, 0.12)',
      '--color-header-bg': 'rgba(255, 255, 255, 0.9)',
    },
  },
  {
    id: 'sapphire',
    name: 'ياقوتي',
    nameEn: 'Sapphire',
    description: 'هادئ ثابت — أزرق كحلي مع لمسات ياقوتية',
    dark: {
      '--color-bg-primary': '#0C0F1E',
      '--color-bg-secondary': '#12162A',
      '--color-bg-tertiary': '#181D36',
      '--color-bg-card': '#14182E',
      '--color-bg-hover': '#1C2140',
      '--color-bg-elevated': '#181D36',
      '--color-text-primary': '#EEEFF5',
      '--color-text-secondary': '#A8ABC0',
      '--color-text-muted': '#6F728A',
      '--color-text-inverse': '#0C0F1E',
      '--color-accent': '#4A7BD4',
      '--color-accent-hover': '#5C8CE3',
      '--color-border': '#1C2140',
      '--color-border-light': '#262B50',
      '--color-border-focus': '#4A7BD4',
      '--color-sidebar-bg': '#0A0C1A',
      '--color-sidebar-hover': '#12162A',
      '--color-sidebar-active': 'rgba(74, 123, 212, 0.12)',
      '--color-header-bg': 'rgba(12, 15, 30, 0.85)',
    },
    light: {
      '--color-bg-primary': '#F8F9FA',
      '--color-bg-secondary': '#F1F3F5',
      '--color-bg-tertiary': '#E9ECEF',
      '--color-bg-card': '#FFFFFF',
      '--color-bg-hover': '#F1F3F5',
      '--color-bg-elevated': '#FFFFFF',
      '--color-text-primary': '#1A1D21',
      '--color-text-secondary': '#6B7280',
      '--color-text-muted': '#9CA3AF',
      '--color-text-inverse': '#FFFFFF',
      '--color-accent': '#2563EB',
      '--color-accent-hover': '#1D4ED8',
      '--color-border': '#E5E7EB',
      '--color-border-light': '#F3F4F6',
      '--color-border-focus': '#2563EB',
      '--color-sidebar-bg': '#1E293B',
      '--color-sidebar-hover': '#334155',
      '--color-sidebar-active': 'rgba(37, 99, 235, 0.12)',
      '--color-header-bg': 'rgba(255, 255, 255, 0.9)',
    },
  },
  {
    id: 'emerald',
    name: 'زمردي',
    nameEn: 'Emerald',
    description: 'طبيعي منعش — أخضر غابي مع زمردي فاتح',
    dark: {
      '--color-bg-primary': '#0A130C',
      '--color-bg-secondary': '#111C14',
      '--color-bg-tertiary': '#17261C',
      '--color-bg-card': '#0E1911',
      '--color-bg-hover': '#1B2E20',
      '--color-bg-elevated': '#17261C',
      '--color-text-primary': '#ECF2EE',
      '--color-text-secondary': '#A3B5A9',
      '--color-text-muted': '#6B7D71',
      '--color-text-inverse': '#0A130C',
      '--color-accent': '#3D9B5A',
      '--color-accent-hover': '#4CAE69',
      '--color-border': '#1B2E20',
      '--color-border-light': '#233A2A',
      '--color-border-focus': '#3D9B5A',
      '--color-sidebar-bg': '#08100A',
      '--color-sidebar-hover': '#111C14',
      '--color-sidebar-active': 'rgba(61, 155, 90, 0.12)',
      '--color-header-bg': 'rgba(10, 19, 12, 0.85)',
    },
    light: {
      '--color-bg-primary': '#F8F9FA',
      '--color-bg-secondary': '#F1F3F5',
      '--color-bg-tertiary': '#E9ECEF',
      '--color-bg-card': '#FFFFFF',
      '--color-bg-hover': '#F1F3F5',
      '--color-bg-elevated': '#FFFFFF',
      '--color-text-primary': '#1A1D21',
      '--color-text-secondary': '#6B7280',
      '--color-text-muted': '#9CA3AF',
      '--color-text-inverse': '#FFFFFF',
      '--color-accent': '#059669',
      '--color-accent-hover': '#047857',
      '--color-border': '#E5E7EB',
      '--color-border-light': '#F3F4F6',
      '--color-border-focus': '#059669',
      '--color-sidebar-bg': '#064E3B',
      '--color-sidebar-hover': '#065F46',
      '--color-sidebar-active': 'rgba(5, 150, 105, 0.12)',
      '--color-header-bg': 'rgba(255, 255, 255, 0.9)',
    },
  },
];

export const DEFAULT_THEME_ID = 'amber';

export function getTheme(id: string): Theme {
  return themes.find((t) => t.id === id) || themes[0];
}

export const sectionAccents: Record<string, string> = {
  '': '#D4893B',
  dashboard: '#D4893B',
  accounts: '#D4893B',
  journal: '#D4893B',
  invoices: '#D4893B',
  'vouchers/receipt': '#D4893B',
  'vouchers/disbursement': '#D4893B',
  cash: '#D4893B',
  'bank-reconciliation': '#D4893B',
  banks: '#4A7BD4',
  currencies: '#4A7BD4',
  'fixed-assets': '#4A7BD4',
  projects: '#3D9B5A',
  boq: '#3D9B5A',
  'progress-billing': '#3D9B5A',
  quotations: '#3D9B5A',
  'purchases/orders': '#2A9D8F',
  'purchases/invoices': '#2A9D8F',
  inventory: '#2A9D8F',
  subcontractors: '#8B5CF6',
  employees: '#D45A7A',
  payroll: '#D45A7A',
  'salary-sheets': '#D45A7A',
  'daily-workers': '#D45A7A',
  custodies: '#D45A7A',
  reports: '#D4A84B',
  settings: '#7A6E7E',
  contacts: '#7A6E7E',
  clients: '#7A6E7E',
  fiscal: '#7A6E7E',
  notifications: '#7A6E7E',
};
