/**
 * Unit tests for admin_users.telegram_bot_token encryption
 * (src/lib/telegram-token-crypto.ts — AES-256-GCM `enc:v1:` envelope).
 *
 * The KAT vector below was generated by the ops-script implementation
 * (scripts/lib/telegram-token-crypto.mjs — `node scripts/lib/telegram-
 * token-crypto.mjs` prints it). Asserting it here pins byte-level
 * compatibility: values written by the scripts decrypt in the app and
 * vice versa. The same vector is self-tested by the migration smoke
 * suite (scripts/test-migrations.mjs → smokeTelegramTokenAtRest).
 */
import {
  TELEGRAM_TOKEN_PREFIX,
  isEncryptedToken,
  parseTokenKey,
  getTokenKeyFromEnv,
  encryptTelegramToken,
  decryptTelegramToken,
} from '@/lib/telegram-token-crypto';

const KAT = {
  key: '00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff',
  iv: '00112233445566778899aabb',
  token: '1234567890:AAKd8sTz4xQ9mPwRvUy2cE3fG5hJ6lN0bXy',
  envelope:
    'enc:v1:ABEiM0RVZneImaq7:0ZtcELkpsME3Ckshc86Z7A==:FN2oOYfI8nRm9ei0+Q+w3ubNA9qsJjO9WNnGNJ1G/inZNvR996U0dMhEhKWRYA==',
};

const ENV_KEY = 'a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90';
const savedKey = process.env.TELEGRAM_TOKEN_KEY;

afterEach(() => {
  if (savedKey === undefined) delete process.env.TELEGRAM_TOKEN_KEY;
  else process.env.TELEGRAM_TOKEN_KEY = savedKey;
});

describe('isEncryptedToken', () => {
  test('true only for strings carrying the enc:v1: prefix', () => {
    expect(isEncryptedToken(KAT.envelope)).toBe(true);
    expect(isEncryptedToken(`${TELEGRAM_TOKEN_PREFIX}a:b:c`)).toBe(true);
    expect(isEncryptedToken('enc:v2:a:b:c')).toBe(false);
    expect(isEncryptedToken('plain-token')).toBe(false);
    expect(isEncryptedToken(null)).toBe(false);
    expect(isEncryptedToken(undefined)).toBe(false);
    expect(isEncryptedToken(42)).toBe(false);
  });
});

describe('parseTokenKey', () => {
  test('accepts 64 hex chars (case-insensitive, trimmed) as 32 raw bytes', () => {
    expect(parseTokenKey(KAT.key).toString('hex')).toBe(KAT.key);
    expect(parseTokenKey(KAT.key.toUpperCase()).toString('hex')).toBe(KAT.key);
    expect(parseTokenKey(`  ${KAT.key}\n`).toString('hex')).toBe(KAT.key);
    expect(parseTokenKey(KAT.key).length).toBe(32);
  });

  test('rejects empty, short, long, and non-hex keys', () => {
    for (const bad of [
      undefined,
      null,
      '',
      ' '.repeat(64),
      KAT.key.slice(0, 63),
      KAT.key + '0',
      'zz'.repeat(32),
      '0123456789abcdef g'.padEnd(64, 'g'),
    ]) {
      expect(() => parseTokenKey(bad)).toThrow('TELEGRAM_TOKEN_KEY must be 64 hex characters');
    }
  });
});

describe('getTokenKeyFromEnv', () => {
  test('parses a valid TELEGRAM_TOKEN_KEY', () => {
    process.env.TELEGRAM_TOKEN_KEY = KAT.key;
    expect(getTokenKeyFromEnv()?.toString('hex')).toBe(KAT.key);
  });

  test('returns null when the key is unset or invalid', () => {
    delete process.env.TELEGRAM_TOKEN_KEY;
    expect(getTokenKeyFromEnv()).toBeNull();
    process.env.TELEGRAM_TOKEN_KEY = 'not-a-key';
    expect(getTokenKeyFromEnv()).toBeNull();
  });
});

describe('encryptTelegramToken', () => {
  test('reproduces the pinned KAT envelope with the pinned IV (≡ .mjs implementation)', () => {
    expect(encryptTelegramToken(KAT.token, { key: KAT.key, iv: Buffer.from(KAT.iv, 'hex') })).toBe(
      KAT.envelope
    );
  });

  test('falls back to the env key when opts.key is absent', () => {
    process.env.TELEGRAM_TOKEN_KEY = ENV_KEY;
    const encrypted = encryptTelegramToken(KAT.token);
    expect(encrypted.startsWith(TELEGRAM_TOKEN_PREFIX)).toBe(true);
    expect(decryptTelegramToken(encrypted)).toBe(KAT.token); // env-key path in decrypt too
  });

  test('rejects empty and over-long tokens, and a missing/invalid key', () => {
    for (const bad of [null, undefined, '', '   ']) {
      expect(() => encryptTelegramToken(bad, { key: KAT.key })).toThrow('Telegram token must not be empty');
    }
    expect(() => encryptTelegramToken('x'.repeat(256), { key: KAT.key })).toThrow('Telegram token too long');
    delete process.env.TELEGRAM_TOKEN_KEY;
    expect(() => encryptTelegramToken(KAT.token)).toThrow('TELEGRAM_TOKEN_KEY must be 64 hex characters');
    expect(() => encryptTelegramToken(KAT.token, { key: 'bad' })).toThrow('TELEGRAM_TOKEN_KEY must be 64 hex characters');
  });

  test('accepts a 255-char token and uses a random IV when opts.iv is invalid', () => {
    const long = '1'.padEnd(255, '2');
    const withBadIv = encryptTelegramToken(long, { key: KAT.key, iv: Buffer.alloc(8) });
    expect(decryptTelegramToken(withBadIv, { key: KAT.key })).toBe(long);

    const randomIv = encryptTelegramToken(KAT.token, { key: KAT.key });
    expect(randomIv).not.toBe(KAT.envelope); // fresh random IV per write
    expect(decryptTelegramToken(randomIv, { key: KAT.key })).toBe(KAT.token);
  });
});

describe('decryptTelegramToken', () => {
  test('null/undefined/empty → null (admin without a dedicated bot)', () => {
    expect(decryptTelegramToken(null)).toBeNull();
    expect(decryptTelegramToken(undefined)).toBeNull();
    expect(decryptTelegramToken('')).toBeNull();
  });

  test('legacy plaintext (no enc:v1: prefix) passes through unchanged', () => {
    expect(decryptTelegramToken('old-plain-token', {})).toBe('old-plain-token');
  });

  test('decodes the KAT envelope — a value written by the .mjs implementation', () => {
    expect(decryptTelegramToken(KAT.envelope, { key: KAT.key })).toBe(KAT.token);
  });

  test('rejects malformed envelopes (part count, IV length, tag length)', () => {
    const b64 = (n: number) => Buffer.alloc(n).toString('base64');
    for (const bad of [
      'enc:v1:onlytwo:parts',
      'enc:v1:a:b:c:d',
      `enc:v1:${b64(8)}:${b64(16)}:${b64(10)}`, // short IV
      `enc:v1:${b64(12)}:${b64(8)}:${b64(10)}`, // short tag
    ]) {
      expect(() => decryptTelegramToken(bad, { key: KAT.key })).toThrow('Malformed encrypted Telegram token');
    }
  });

  test('rejects a tampered ciphertext, a wrong key, and a missing key', () => {
    // envelope = 'enc:v1:<iv>:<tag>:<ct>' → split(':') has 5 parts.
    const [, , ivB64, tagB64, ctB64] = KAT.envelope.split(':');
    const flipped = ctB64.slice(0, 2) + (ctB64[2] === 'A' ? 'B' : 'A') + ctB64.slice(3);
    expect(() => decryptTelegramToken(`enc:v1:${ivB64}:${tagB64}:${flipped}`, { key: KAT.key })).toThrow();
    expect(() => decryptTelegramToken(KAT.envelope, { key: ENV_KEY })).toThrow();
    delete process.env.TELEGRAM_TOKEN_KEY;
    expect(() => decryptTelegramToken(KAT.envelope)).toThrow('TELEGRAM_TOKEN_KEY must be 64 hex characters');
  });
});
