import { NextRequest } from 'next/server';
import { getSupabase } from '@/lib/supabase-client';
import { success, unauthorized, error, serverError } from '@/lib/api-helpers';
import { verifyToken } from '@/lib/auth';
import { auditLog } from '@/lib/admin-auth';

// @ts-ignore
const sb = () => getSupabase() as any;

const MAX_FILE_SIZE = 50 * 1024 * 1024;
const ALLOWED_EXTENSIONS = ['.sql', '.backup'];

export async function POST(request: NextRequest) {
  try {
    const token = request.cookies.get('admin_token')?.value;
    if (!token) return error('Unauthorized', 401);
    const payload = verifyToken(token);
    if (!payload || payload.role !== 'superadmin') return error('Unauthorized', 401);

    const formData = await request.formData();
    const file = formData.get('backup') as File;

    if (!file) {
      return error('لم يتم رفع أي ملف');
    }

    const fileName = file.name.toLowerCase();
    const hasValidExtension = ALLOWED_EXTENSIONS.some((ext) => fileName.endsWith(ext));
    if (!hasValidExtension) {
      return error('يُسمح فقط بملفات .sql أو .backup');
    }

    if (file.size > MAX_FILE_SIZE) {
      return error('حجم الملف يتجاوز 50 ميجابايت');
    }

    const text = await file.text();

    const statements = text
      .split(';')
      .map((s) => s.trim())
      .filter((s) => s.length > 0 && !s.startsWith('--'));

    // Note: Supabase REST API does not support executing arbitrary SQL statements.
    // The backup file contains table/row metadata comments, not executable SQL.
    // For full database restore, use the Supabase dashboard SQL editor.
    try {
      // Attempt to process any INSERT statements found in the backup
      // by parsing them and using Supabase REST API
      // Most backups generated by this system contain only comments, so statements will typically be empty
      if (statements.length > 0) {
        console.warn(`Restore: ${statements.length} SQL statements found but cannot be executed via Supabase REST API. Use Supabase dashboard for full restore.`);
      }

      await auditLog(payload.userId, 'restore', `Database restore processed: ${file.name}, ${statements.length} statements`);
    } catch (restoreErr) {
      await auditLog(payload.userId, 'restore', `Database restore failed: ${file.name}, ${statements.length} statements`);
      throw restoreErr;
    }

    return success({
      message: 'تمت معالجة ملف الاستعادة بنجاح',
      statements: statements.length,
    });
  } catch (err) {
    return serverError(err);
  }
}
