'use client';
import { useEffect, useState } from 'react';
import { Sparkles, RefreshCw, Save, ChevronLeft } from 'lucide-react';
import Link from 'next/link';

type Company = { id:string; name:string; optional_features?:Record<string,boolean>; additional_users_limit?:number };
export default function OptionalFeaturesPage() {
 const [companies,setCompanies]=useState<Company[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState<string|null>(null);
 const load=async()=>{setLoading(true); const r=await fetch('/api/admin/optional-features'); const b=await r.json(); if(b.success)setCompanies(b.data.companies||[]); setLoading(false);};
 useEffect(()=>{load()},[]);
 const update=(id:string, patch:Partial<Company>&{taxBarcode?:boolean;additionalUsers?:boolean;additionalUsersLimit?:number})=>setCompanies(cs=>cs.map(c=>c.id===id?{...c,optional_features:{...c.optional_features,...(patch.taxBarcode!==undefined?{tax_barcode:patch.taxBarcode}:{}),...(patch.additionalUsers!==undefined?{additional_users:patch.additionalUsers}:{})},additional_users_limit:patch.additionalUsersLimit??c.additional_users_limit}:c));
 const save=async(c:Company)=>{setSaving(c.id); const r=await fetch('/api/admin/optional-features',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId:c.id,taxBarcode:!!c.optional_features?.tax_barcode,additionalUsers:!!c.optional_features?.additional_users,additionalUsersLimit:Number(c.additional_users_limit||0)})}); if(!r.ok) alert((await r.json()).message||'فشل الحفظ'); setSaving(null);};
 return <div className="min-h-full bg-bg-primary"><div className="max-w-6xl mx-auto px-4 py-6"><div className="flex items-center justify-between mb-6"><div className="flex items-center gap-3"><Link href="/zerocold" className="p-2 rounded-lg hover:bg-bg-card"><ChevronLeft size={18}/></Link><Sparkles className="text-accent"/><div><h1 className="text-lg font-bold">مميزات إضافية</h1><p className="text-xs text-text-muted">تفعيل المميزات لكل شركة بشكل يدوي — كل ميزة جديدة معطلة افتراضياً</p></div></div><button onClick={load} className="p-2 rounded-xl bg-bg-card border border-border"><RefreshCw size={16}/></button></div><div className="bg-accent/10 border border-accent/20 rounded-xl p-4 mb-5 text-sm text-text-secondary">الحد الأقصى للمستخدمين الإضافيين ١٠. لا يتم احتساب أي مستخدم إضافي إلا بعد تفعيل الميزة وتحديد العدد.</div>{loading?<p>جاري التحميل...</p>:<div className="bg-bg-card border border-border rounded-xl overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-border text-xs text-text-muted"><th className="p-4 text-right">الشركة</th><th className="p-4">الباركود الضريبي</th><th className="p-4">المستخدم الإضافي</th><th className="p-4">العدد المسموح</th><th className="p-4">حفظ</th></tr></thead><tbody>{companies.map(c=><tr key={c.id} className="border-b border-border last:border-0"><td className="p-4 text-sm font-medium">{c.name}</td><td className="p-4 text-center"><input type="checkbox" checked={!!c.optional_features?.tax_barcode} onChange={e=>update(c.id,{taxBarcode:e.target.checked})}/></td><td className="p-4 text-center"><input type="checkbox" checked={!!c.optional_features?.additional_users} onChange={e=>update(c.id,{additionalUsers:e.target.checked})}/></td><td className="p-4 text-center"><input type="number" min="0" max="10" value={c.additional_users_limit||0} onChange={e=>update(c.id,{additionalUsersLimit:Math.min(10,Math.max(0,Number(e.target.value)||0))})} className="w-20 text-center bg-bg-secondary border border-border rounded-lg p-2"/></td><td className="p-4 text-center"><button onClick={()=>save(c)} disabled={saving===c.id} className="inline-flex items-center gap-2 px-3 py-2 rounded-lg bg-accent text-white text-xs"><Save size={14}/>{saving===c.id?'جاري...':'حفظ'}</button></td></tr>)}</tbody></table></div>}</div></div>;
}
